class BadWords {
  // static List<String> english = [
  //   "Fuck", "Fuck You", "Shit", "Piss off", "Dick head", "Asshole",
  //   "Son of a bitch", "Bastard", "Bitch", "Damn", "Dumb", "Nerd",
  //   "Ginger", "Bimbo", "Jock", "Piss", "Jerk", "Stupid", "Wimp",
  //   "Lame", "Idiot", "Fool", "Retard", "Loser", "Pain in the Neck",
  //   "Rubbish", "Shag", "Wanker", "Taking the Piss", "Twat",
  //   "Bollocks", "Bugger", "Choad", "Crikey", "Bloody Hell",
  //   "Bloody Oath", "Root", "Get Stuffed", "Bugger",  "Cheesy",
  //   "Crazy", "Creepy", "Clown", "Weird"
  // ];
  //

  static List<String> english = [
    "FUCK",
    "FUCKER",
    "FUCKERS",
    "FUCKING",
    "FUCKS",
    "FUCKED",
    "FUCKOFF",
    "FUCKUP",
    "FUCKFACE",
    "FUCKHEAD",
    "FUCKWIT",
    "FUCKBOY",
    "FUCKGIRL",
    "MOTHERFUCK",
    "MOTHERFUCKER",
    "MOTHERFUCKING",
    "BITCH",
    "BITCHES",
    "BITCHY",
    "SONOFABITCH",
    "CUNT",
    "CUNTS",
    "ASS",
    "ASSES",
    "ASSHOLE",
    "ASSHOLES",
    "DICK",
    "DICKS",
    "COCK",
    "COCKS",
    "PUSSY",
    "PUSSIES",
    "BASTARD",
    "BASTARDS",
    "WHORE",
    "WHORES",
    "SLUT",
    "SLUTS",
    "PRICK",
    "PRICKS",
    "TWAT",
    "TWATS",
    "WANK",
    "WANKER",
    "TITS",
    "BOOBS",
    "DILDO",
    "DILDOS",
    "ANAL",
    "BLOWJOB",
    "HANDJOB",
    "RIMJOB",
    "CUM",
    "CUMSHOT",
    "JIZZ",
    "SPUNK",
    "RAPE",
    "RAPIST",
    "KILL",
    "MURDER",
    "SUICIDE",
    "TERRORIST",
    "BOMB",
    "NAZI",
    "DRUG",
    "COCAINE",
    "HEROIN",
    "CRACK",
    "METH",
    "SHIT",
    "SHITS",
    "BULLSHIT",
    "PISS",
    "LOSER",
    "UGLYASS",
    "SEXIST",
    "RACIST",
    "FAG",
    "NIGGER",
    "RETARD",
    "CRIPPLE",
    "IDIOT",
    "STUPID",
    "HOOKER",
    "PROSTITUTE",
    "PORNSTAR",
    "SEXSLAVE",
  ];

  static const List<String> italian = [
    "CAZZO",
    "CAZZI",
    "CAZZATA",
    "CAZZATE",
    "MINCHIA",
    "MINCHIONE",
    "FIGA",
    "FIGHE",
    "FREGNA",
    "FICA",
    "FOTTITI",
    "FOTTERE",
    "FOTTUTO",
    "VAFFANCULO",
    "FANCULO",
    "INCULO",
    "CULATTONE",
    "CULO",
    "CULI",
    "PUTTANA",
    "PUTTANE",
    "MIGNOTTA",
    "TROIA",
    "TROIE",
    "STRONZO",
    "STRONZA",
    "STRONZI",
    "COGLIONE",
    "COGLIONI",
    "BASTARDO",
    "BASTARDI",
    "MERDA",
    "MERDE",
    "CAGATA",
    "CACCA",
    "PISCIO",
    "PETO",
    "CORNUTO",
    "SEGHE",
    "POMPINO",
    "SBORRA",
    "SCOPARE",
    "TROMBARE",
    "CHIAVARE",
    "STUPRO",
    "PEDOFILO",
    "NEGRO",
    "ZINGARO",
    "FROCIO",
    "RICCHIONE",
    "DEFICIENTE",
    "CRETINO",
    "IDIOTA",
    "SCEMO",
    "TERRORISTA",
    "NAZISTA",
    "FASCISTA",
    "RAZZISTA",
    "COCAINA",
    "EROINA",
    "DROGATO",
    "SPACCIATORE",
    "OVERDOSE",
    "STRAGISTA",
    "GENOCIDIO",
  ];

  // static List<String> italian = [
  //   "Cazzo", "Vaffanculo", "Merda", "Vattene al diavolo", "Testa di cazzo",
  //   "Stronzo", "Figlio di puttana", "Bastardo", "Puttana", "Dannazione",
  //   "Stupido", "Secchione", "Rosso", "Oca", "Palestrato", "Piscia",
  //   "Idiota", "Stupido", "Fifone", "Sfigato", "Idiota", "Sciocco",
  //   "Ritardato", "Perdente", "Rompiscatole", "Spazzatura", "Scopare",
  //   "Segaiolo", "Prendere in giro", "Coglione", "Cazzate", "Fregato",
  //   "Coglione", "Accidenti", "Porca miseria", "Altroché", "Scopare",
  //   "Fatti da parte", "Fregato", "Sdolcinato", "Pazzo", "Inquietante",
  //   "Pagliaccio", "Strano"
  // ];
}
