final Map<String, String> italian = {
  // -------- Welcome Screen --------
  'splash': 'COLLEGAMENTO DEI PILOTI UNA PIASTRA ALLA VOLTA',

  //'welcome_message': 'La tua Targa,\n la tua chat',
  'welcome_message': 'La tua Targa, la tua chat',
  //'welcome_message1': "Vedi una targa, inizia a chattare:",
  'welcome_message1': "Vedi una targa, inizi a chattare:",
  //'welcome_message2': "registrati velocemente e connettiti",
  'welcome_message2': "registrati velocemente e connettiti con un",
  //'welcome_message3': "con un driver ovunque tu vada",
  //'welcome_message3': "driver ovunque tu vada",
  'welcome_message3': "PLATEChatter ovunque tu vada",

  'sign_up': 'Registrati',
  'log_in': 'Accedi',
  'sign_in': 'Accedi',
  'do_not_account': "Non hai un account? ",
  'already_account1': "Hai già un account? ",

  // -------- Sign In --------
  'nick_name': 'Soprannome',
  'license_number_title': "Numero di Targa",
  'license_number1': "Targa",
  'license_plate_or_nick_name': 'Targa o Nickname',
  'enter_license_plate_or_nick_name': 'Inserisci la targa o il nickname',
  'password': 'Password',
  'enter_your_password': 'Inserisci la tua password',
  'password_is_required': 'La password è obbligatoria',
  'password_must_6_character': 'La password deve contenere almeno 6 caratteri',
  'forgot_password': 'Password dimenticata',
  "license_plate_or_nickname_required": "Targa o Nickname obbligatori",

  // -------- Sign Up --------
  'nickname_is_required': 'Il nickname è obbligatorio',
  'select_designation': 'Scegli Ruolo',
  'select': 'Seleziona',
  'owner': 'Proprietario',
  'occasional_driver': 'Guidatore occasionale',
  'please_select_designation': 'Seleziona un ruolo',
  'nick_name_hint': 'Nome',
  'license_number': 'Numero di targa',
  'type_here': 'Scrivi qui',
  'license_number_is_required': 'Il numero di licenza è obbligatorio',
  'license_number_must_be': 'La targa non è corretta',
  'license_number_required': 'È richiesta la Targa',

  'confirm_password': 'Conferma password',
  'confirm_your_password': 'Conferma la tua password',
  'password_do_not_match': 'Le password non corrispondono',
  'i_agree_to': 'Dichiaro di avere almeno 16 anni e accetto i',
  'agree_terms': 'Termini e Condizioni e Informativa sulla Privacy',
  'continue': 'Continua',
  'please_fill_all_fields': 'Compila tutti i campi',
  //'please accept terms': 'Accetta i termini',
  'please accept terms': 'Per continuare devi accettare i termini',
  'creating_account': 'Creazione account...',
  'registration_successful!': 'Registrazione completata con successo!',

  'age_confirmation': "Conferma la tua età",
  //'16_or_not': 'Hai 16 anni?',
  '16_or_not': 'Hai almeno 16 anni?',

  'yes': "SÌ",
  'no': "NO",
  'email_only_for_recover_password': "Email solo per recuperare la password",

  'i_agree_to1':
      "Acconsento all'utilizzo dei miei dati per ulteriori finalità -",
  'agree_terms1': "Ulteriori informazioni",
  "email_is_required": "Email obbligatoria",
  "enter_valid_email": "Inserisci un indirizzo email valido",

  //------------------------------------------------------
  "don't_worry_enter_your_email":
      "Non preoccuparti, inserisci la tua email registrata",
  "enter_your_email_here": "Inserisci qui la tua email",
  'send_otp': 'Invia OTP',
  'email': "E-mail",
  'enter_verification_code': "Inserisci il codice di verifica",
  'verification_code': 'Codice di verifica',
  'we_sent_6_digit_code': 'Abbiamo inviato un codice a 6 cifre',

  'send': "Invia",
  'reset_code': "Codice di reset",
  'new_password': 'Nuova password',
  'save': 'Salva',

  //-------------------------------------------------------------
  'or': 'OPPURE',
  'already_account': 'Hai già un account?',

  'terms_and_conditions': 'Termini e Condizioni',
  'log_out': 'Disconnetti',

  // ------------------All chat-------------------------
  'all_chat': 'Tutte le chat',
  'search_here': 'Cerca qui',
  'no_chats': 'Nessuna chat ancora',

  // ------------------Message Screen-------------------------
  'view_profile': 'Visualizza profilo',
  'rate_user': 'Valuta utente',
  'no_messages_yet': 'Nessun messaggio ancora',
  'no_recents_yet': 'Nessuna recente ancora',
  'rating_poor': 'Scarso',
  'rating_fair': 'Sufficiente',
  'rating_good': 'Buono',
  'rating_great': 'Ottimo',
  'rating_excellent': 'Eccellente',
  'add_comment': 'Aggiungi un commento (opzionale)...',
  'submit_rating': 'Invia valutazione',
  'update_rating': 'Aggiorna valutazione',
  'tap_to_rate': 'Tocca una stella per valutare',
  'update_your_rating': 'Aggiorna la tua valutazione',
  'rating_submitted': 'Valutazione inviata',
  'rating_updated': 'Valutazione aggiornata',
  'rating_failed': 'Impossibile salvare la valutazione',

  // ------------------Group Chat Dialog-------------------------
  'create_group_chat': 'Crea chat di gruppo',
  'group_chat_subtitle': 'Connettiti con più persone contemporaneamente',
  'group_name': 'Nome del gruppo *',
  'please_enter_group_name': 'Inserisci un nome per il gruppo',
  'group_name_min_chars': 'Il nome del gruppo deve contenere almeno 3 caratteri',
  'enter_group_name': 'Inserisci il nome del gruppo...',
  'create_group': 'Crea gruppo',
  'type_here1': "Scrivi qui",
  'block_': "Blocca",
  //'block_': "Sblocca",
  //"blocked_user": "Utente bloccato",
  "blocked_user1": "Sblocca",
  "add_rating":"Aggiungi valutazione",
  "blocked_user5": "Utenti bloccati",

  "unblock": "Sblocca",
  'logout': "Esci",
  'profile': "Profilo",
  "edit": "Modificare",
  'and': ' e le ',
  "privacy_policy": "Politiche sulla riservatezza",
  "you_can't_send": "Non puoi inviare un messaggio a questo utente",
  "you've_blocked": "Hai bloccato",
  "this_user_won't_be_able":
      "Questo utente non potrà inviarti messaggi finché non lo sbloccherai.",
  'language': 'Lingua',
  'nickname': 'Soprannome',
  "email_required": "L'e-mail è obbligatoria",
  "new_pass_required": "È richiesta una nuova password",
  "confirmed_pass_required": "È richiesta la conferma della password",
  "pass_not_match": "La password non corrisponde",
  "pass_six_char": "La password deve contenere almeno 6 caratteri",
  "otp_required": "L'OTP è obbligatorio",
  'empty_block_list': 'Elenco utenti bloccati vuoto',
  'remember_me': "Ricordami",
  "bad_word_error": "Questi messaggio contiene parole inappropriate.",
  "only_for_recovery": "recupero account",
  "please_enter_valid_email": "Inserisci una mail valida",
  "otp_verify_success": "OTP verificata con successo",
  "something_went_wrong": "Qualcosa è andato storto",
  "user_not_found": "Utente non trovato",
  "otp_send_success": "OTP inviata con successo",
  "password_reset_successfully": "Reimpostazione della password riuscita",
  "user_unblocked_successfully": "Utente sbloccato con successo",
  "failed_to_unblock_user": "Impossibile sbloccare l'utente",
  "info": 'Informazioni',
  'please_select_an_image_first': "Seleziona prima un'immagine",
  "success": "Successo",
  "profile_image_updated_successfully":
      'Immagine del profilo aggiornata con successo',
  'error': "Errore",
  "failed_to_update_profile_image":
      "Impossibile aggiornare l'immagine del profilo",
  "error_updating_profile:": "Errore durante l'aggiornamento del profilo:",
  "user_blocked_successfully": "Utente bloccato con successo",
  "failed_to_block_user": "Impossibile bloccare l'utente",
  "password_must_be_6_characters":
      "La password deve contenere almeno 6 caratteri",
  "delete": "Elimina account",

  "delete_account": "Elimina account",
  "warning": "Avvertimento",
  "delete_account_warning": "Avviso di eliminazione dell'account",
  "delete_account_successfully": "Account eliminato con successo",
  "failed_delete_account": "Impossibile eliminare l'account",
  "help_support": "Aiuto e Supporto",
  "support_text1": "Per qualsiasi aiuto e supporto, contattaci a ",
  "client_email": "support@platechat.app",
  "support_text2":
      "Il nostro team di supporto è disponibile per assisterti con qualsiasi problema o richiesta.",
  "support_request": "Richiesta di supporto",
  "email_copied": "E-mail copiata",

  // Toast message
  'invalid_credentials': 'Credenziali non valide!',
  'something_wrong': 'Qualcosa è andato storto!',
  'success1': 'Operazione riuscita!',
  'error2': 'Si è verificato un errore!',
  'unauthorized': 'Non autorizzato!',
  'session_expired': 'Sessione scaduta!',
  'network_error': 'Errore di rete!',
  'not_found': 'Non trovato!',
  'saved': 'Salvato!',
  'deleted': 'Eliminato!',
  'updated': 'Aggiornato!',
  'created': 'Creato!',
  'load_failed': 'Caricamento fallito!',
  'upload_success': 'Caricato!',
  'upload_failed': 'Caricamento fallito!',
  'server_error': 'Errore del server!',
  'login_success': 'Bentornato!',
  'logout_success': 'Disconnesso!',
  'no_data': 'Nessun dato!',
  'dismiss': 'Annulla',

  // ------------------Profile Screen-------------------------
  'upload_documents': 'Carica documenti',
  'drivers_license': 'Patente di guida',
  'car_insurance': 'Assicurazione auto',
  'car_tax': 'Bollo auto',
  'tap_to_upload': 'Tocca per caricare',
  'view_document': 'Vedi file attuale',
  'update': 'Aggiorna',
  'renew': 'Rinnova',
  'expires': 'Scadenza',
  'expired': 'Scaduto',
  'days_left': 'giorni rimanenti',
  'id': 'ID',

  // ------------------Scan Screen-------------------------
  'scan_qr': 'Scansiona QR',
  'my_qr': 'Il mio QR',
  'point_camera_hint': "Punta la fotocamera sul codice QR di un altro utente per connetterti immediatamente.",
  'let_others_scan': 'Lascia che altri conducenti scansionino questo per chattare con te.',
  'show_qr_to_connect': 'Mostra questo QR per connetterti',
  'camera_permission_denied': 'Permesso fotocamera negato.\nAbilitalo nelle Impostazioni.',
  'camera_unsupported': 'Fotocamera non supportata\nsu questo dispositivo.',
  'camera_error': 'Errore fotocamera.\nRiavvia l\'app.',

  // ------------------Profile Card-------------------------
  'give_rating': 'Dai una valutazione',
  'start_chat': 'Inizia chat',

  // ------------------Profile Nav Screen-------------------------
  'upload': 'Carica',
  'useful_number': 'Numero utile',
  "drop_parking_pin":"Rilascia il contrassegno di parcheggio",
  "remove_pin":"Rimuovere il perno di parcheggio",
  "map_getting_location": "Recupero posizione...",
  "map_loading_parking_spots": "Caricamento parcheggi...",
  "map_selected_report": "Segnalazione selezionata",
  "map_parking_details": "Dettagli parcheggio",
  "map_parking_cost": "Costo parcheggio",
  "map_electric_charging": "Ricarica elettrica",
  "map_disabled_facility": "Struttura disabili",
  "map_disabled_parking_location": "Posizione parcheggio disabili",
  "map_drop_pin": "Posiziona pin",
  "map_cancel": "Annulla",
  "map_all": "TUTTO",
  "map_back": "DIETRO",
  "map_right": "DESTRA",
  "map_left": "SINISTRA",
  "map_none": "NESSUNO",
  "map_parking_report_submitted": "Segnalazione parcheggio inviata!",
  "map_failed_to_submit_parking_report": "Invio segnalazione parcheggio non riuscito",
  "map_parking_pin": "Pin parcheggio",
  "map_paid_parking": "Parcheggio a pagamento",
  "map_free_parking": "Parcheggio gratuito",
  "map_failed_to_load_parking_data": "Caricamento dati parcheggio non riuscito",
  "map_cost": "Costo",
  "map_ev": "EV",
  "map_disabled": "Disabili",
  "scan": "Scansiona",
  "chat":"chiacchierata",
  "map":"mappa",
  "you":"Voi",
  // -------- Group Message App Bar --------
  'members': 'membri',
  'leave_group': 'Lascia il gruppo',
  'leave_group_confirmation': 'Sei sicuro di voler lasciare',
  'cancel': 'Annulla',
  'leave': 'Lascia',
  'see_members': 'Vedi membri',
  'add_members': 'Aggiungi membri',

  //see members

  'remove_member': 'Rimuovi membro',
  'remove_member_confirmation': 'Rimuovere dal gruppo',
  'remove': 'Rimuovi',
  'no_members_found': 'Nessun membro trovato',
//add member
  'add_member': 'Aggiungi membro',
  'no_results_for': 'Nessun risultato per',
  'no_contacts_found': 'Nessun contatto trovato',
  //use full



  'retry': 'Riprova',
  'no_useful_numbers_found': 'Nessun numero utile trovato nelle vicinanze.',
  'loading': 'Caricamento...',
  'map_free': 'Gratuito',
  'map_paid': 'A pagamento',

  //scan

  'existing_chat': 'Chat esistente',
  'new_user': 'Nuovo utente',
  'open_chat': 'Apri chat',
  "no_messages":"Nessun messaggio ancora",
  'tap_to_retry': 'Tocca per riprovare',
  'profile_not_found': 'Profilo non trovato',

  //profile upload


  'upload_document': 'Carica Documento',
  'update_document': 'Aggiorna Documento',
  'unique_number': 'Numero Univoco',
  'expire_date': 'Data di Scadenza',
  'upload_file': 'Carica File',
  'replace_file': 'Sostituisci File',

  'tap_to_select_file': 'Tocca per selezionare il file',
  'pdf_jpg_png_doc_supported': 'PDF, JPG, PNG, DOC supportati',
  'please_enter_unique_number': 'Inserisci un numero univoco',
  'please_enter_expire_date': 'Inserisci una data di scadenza',
  'please_select_file': 'Seleziona un file',
  'please_select_new_file': 'Seleziona un nuovo file',
  'could_not_open_document': 'Impossibile aprire il documento',
  'dd_mm_yyyy': 'GG/MM/AAAA',
  'unique_number_hint': '123456789',


};
