final Map<String, String> italian = {
  // -------- Welcome Screen --------
  'splash': 'COLLEGAMENTO DEI PILOTI UNA PIASTRA ALLA VOLTA',

  //'welcome_message': 'La tua Targa,\n la tua chat',
  'welcome_message': 'La tua Targa, la tua chat',
  //'welcome_message1': "Vedi una targa, inizia a chattare:",
  'welcome_message1': "Vedi una targa, inizi a chattare:",
  //'welcome_message2': "registrati velocemente e connettiti",
  'welcome_message2': " registrati velocemente e connettiti con un",
  //'welcome_message3': "con un driver ovunque tu vada",
  'welcome_message3': "driver ovunque tu vada",

  'sign_up': 'Registrati',
  'log_in': 'Accedi',
  'sign_in': 'Accedi',
  'do_not_account': "Non hai un account? ",
  'already_account1': "Hai già un account? ",

  // -------- Sign In --------
  'nick_name': 'Nickname',
  'license_number_title':"Numero di Targa",
  'license_number1':"Targa",
  'license_plate_or_nick_name': 'Targa o Nickname',
  'enter_license_plate_or_nick_name': 'Inserisci la targa o il nickname',
  'password': 'Password',
  'enter_your_password': 'Inserisci la tua password',
  'password_is_required': 'La password è obbligatoria',
  'password_must_6_character': 'La password deve contenere almeno 6 caratteri',
  'forgot_password': 'Password dimenticata',

  // -------- Sign Up --------
  'nickname_is_required': 'Il nickname è obbligatorio',
  'select_designation': 'Scegli Ruolo',
  'select': 'Seleziona',
  'owner': 'Proprietario',
  'occasional_driver': 'Guidatore occasionale',
  'please_select_designation': 'Seleziona un ruolo',
  'nick_name_hint': 'Nome',
  'license_number': 'Numero di targa',
  'type_here': 'Scrivi qui',
  'license_number_is_required': 'Il numero di licenza è obbligatorio',
  'license_number_must_be': 'La targa non è corretta',
  'license_number_required': 'È richiesto il numero di licenza',

  'confirm_password': 'Conferma password',
  'confirm_your_password': 'Conferma la tua password',
  'password_do_not_match': 'Le password non corrispondono',
  'i_agree_to': 'Dichiaro di avere almeno 16 anni e accetto i',
  'agree_terms': 'Termini e Condizioni e Informativa sulla Privacy',
  'continue': 'Continua',
  'please_fill_all_fields': 'Compila tutti i campi',
  'please accept terms': 'Accetta i termini',
  'creating_account': 'Creazione account...',
  'registration_successful!': 'Registrazione completata con successo!',

  'age_confirmation': "Conferma la tua età",
  '16_or_not': 'Hai 16 anni?',
  'yes': "SÌ",
  'no': "NO",
  'email_only_for_recover_password': "Email solo per recuperare la password",

  'i_agree_to1':
      "Acconsento all'utilizzo dei miei dati per ulteriori finalità -",
  'agree_terms1': "Ulteriori informazioni",

  //------------------------------------------------------
  "don't_worry_enter_your_email":
      "Non preoccuparti, inserisci la tua email registrata",
  "enter_your_email_here": "Inserisci qui la tua email",
  'send_otp': 'Invia OTP',
  'email': "E-mail",
  'enter_verification_code': "Inserisci il codice di verifica",
  'verification_code': 'Codice di verifica',
  'we_sent_6_digit_code': 'Abbiamo inviato un codice a 6 cifre',

  'send': "Inviare",
  'reset_code': "Codice di reset",
  'new_password': 'Nuova password',
  'save': 'Salva',

  //-------------------------------------------------------------
  'or': 'OPPURE',
  'already_account': 'Hai già un account?',

  'terms_and_conditions': 'Termini e Condizioni',
  'log_out': 'Disconnetti',

  // ------------------All chat-------------------------
  'all_chat': 'Tutte le chat',
  'search_here': 'Cerca qui',
  'type_here1': "Scrivi qui",
  'block_': "Blocca",
  //'block_': "Sblocca",
  //"blocked_user": "Utente bloccato",
  "blocked_user1": "Sblocca",
  "unblock": "Sblocca",
  'logout': "Esci",
  'profile': "Profilo",
  "edit": "Modificare",
  'and': ' e le ',
  "privacy_policy": "Politiche sulla riservatezza",
  "you_can't_send": "Non puoi inviare un messaggio a questo utente",
  "you've_blocked": "Hai bloccato",
  "this_user_won't_be_able":
      "Questo utente non potrà inviarti messaggi finché non lo sbloccherai.",
  'language': 'Lingua',
  'nickname': 'Soprannome',
  "email_required": "L'e-mail è obbligatoria",
  "new_pass_required": "È richiesta una nuova password",
  "confirmed_pass_required": "È richiesta la conferma della password",
  "pass_not_match": "La password non corrisponde",
  "pass_six_char": "La password deve contenere almeno 6 caratteri",
  "otp_required": "L'OTP è obbligatorio",
  'empty_block_list': 'Elenco blocchi vuoto',
  'remember_me': "Ricordami",
  "bad_word_error": "Questi messaggio contiene parole inappropriate.",
  "only_for_recovery": "recupero account",
  "please_enter_valid_email": "Si prega di inserire un indirizzo email valido",
  "otp_verify_success": "OTP verificata con successo",
  "something_went_wrong": "Qualcosa è andato storto",
  "user_not_found": "Utente non trovato",
  "otp_send_success": "OTP inviata con successo",
  "password_reset_successfully": "Reimpostazione della password riuscita",
  "user_unblocked_successfully": "Utente sbloccato con successo",
  "failed_to_unblock_user": "Impossibile sbloccare l'utente",
  "info": 'Informazioni',
  'please_select_an_image_first': "Seleziona prima un'immagine",
  "success": "Successo",
  "profile_image_updated_successfully":
      'Immagine del profilo aggiornata con successo',
  'error': "Errore",
  "failed_to_update_profile_image":
      "Impossibile aggiornare l'immagine del profilo",
  "error_updating_profile:": "Errore durante l'aggiornamento del profilo:",
  "user_blocked_successfully": "Utente bloccato con successo",
  "failed_to_block_user": "Impossibile bloccare l'utente",
  "password_must_be_6_characters":
      "La password deve contenere almeno 6 caratteri",
  "delete": "eliminare",


  "delete_account":"Elimina account",
  "warning":"Avvertimento",
  "delete_account_warning":"Avviso di eliminazione dell'account",
  "delete_account_successfully":"Account eliminato con successo",
  "failed_delete_account":"Impossibile eliminare l'account",
  "help_support":"Aiuto e supporto",

};
